[tool.poetry]
name = "safepay-wallet-mcp"
version = "0.1.0"
description = "SafePay Wallet MCP server for travel optimization"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
mcp = "^1.0.0"
fastapi = "^0.109.0"
uvicorn = "^0.27.0"
pydantic = "^2.6.0"
redis = "^5.0.1"
httpx = "^0.27.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api" 