[project]
name = "shared"
version = "0.1.0"
description = "Shared models and utilities for the travel optimization application"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.6.0",
    "python-dotenv>=1.0.0",
    "loguru>=0.7.2"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
python = "3.12" 