version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  chase-travel-mcp:
    build:
      context: .
      dockerfile: packages/mcp_servers/chase_travel/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  safepay-wallet-mcp:
    build:
      context: .
      dockerfile: packages/mcp_servers/safepay_wallet/Dockerfile
    ports:
      - "8002:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  benefits-mcp:
    build:
      context: .
      dockerfile: packages/mcp_servers/benefits/Dockerfile
    ports:
      - "8003:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  optimization-agent:
    build:
      context: .
      dockerfile: packages/optimization_agent/Dockerfile
    environment:
      - CHASE_TRAVEL_MCP_URL=http://chase-travel-mcp:8000
      - SAFEPAY_WALLET_MCP_URL=http://safepay-wallet-mcp:8000
      - BENEFITS_MCP_URL=http://benefits-mcp:8000
    depends_on:
      - chase-travel-mcp
      - safepay-wallet-mcp
      - benefits-mcp

volumes:
  redis_data: 